"""Add user_id to emails

Revision ID: d1eb0b652cca
Revises: b7c929bcab92
Create Date: 2026-01-10 20:17:21.055492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1eb0b652cca'
down_revision: Union[str, Sequence[str], None] = 'b7c929bcab92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'emails', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emails', type_='foreignkey')
    op.drop_column('emails', 'user_id')
    # ### end Alembic commands ###
